on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux']
        arch: ['amd64', 'arm', 'arm64', 'riscv64']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: "Build peerd for ${{ matrix.os }}-${{ matrix.arch }}"
        run: |
          mkdir out/
          go build -o out/peerd.${{ matrix.os }}-${{ matrix.arch }} ./cmd/peerd
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: peerd.${{ matrix.os }}-${{ matrix.arch }}
          path: 'out/'
          if-no-files-found: error
          retention-days: 1

  release:
    needs:
    - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: semver
        uses: thenativeweb/get-next-version@2.7.1
        with:
          prefix: 'v'

      - id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
        continue-on-error: true

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.ref_name }}
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      - uses: actions/download-artifact@v4
        with:
          path: out/
          merge-multiple: true

      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.version }}
          prerelease: false
          name: ${{ steps.semver.outputs.version }}
          body: ${{ steps.changelog.outputs.changes || 'Initial Release' }}
          files: |
            out/*
          fail_on_no_files: true
